In [ ]:
import numpy as np

M1 = np.array([[0, 1, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 1],
               [0, 0, 0, 0]], dtype=bool)

M2 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, 0, 0],
               [0, 0, 0]], dtype=bool)

#  nhân ma trận: M1 x M2
M = M1.dot(M2)
np.array(M, dtype=int)

array([[0, 1, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
import numpy as np

M = np.array([[0, 1, 1, 0],
              [0, 0, 0, 1],
              [0, 1, 0, 0],
              [0, 0, 0, 0]], dtype=bool)

n = len(M)
L = M.copy()

# tính ma trận M ^ 2, 3, 4, ...
for k in range(2, n + 1):
    L = M.dot(L) # lưu M^ k
    print(k, np.array(L, dtype=int))


2 [[0 1 0 1]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]
3 [[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
4 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
import numpy as np
# R bắc cầu
M = np. array ([[0, 1, 1, 0],
                [0, 1, 0, 1],
                [0, 1, 0, 0],
                [0, 1, 0, 0]] , dtype = bool )
n = len (M)
A = M. copy ()
L = M. copy ()
for k in range (2, n+1) :
    L = M. dot (L) # lưu M^ k
    A += L # lưu M + M^ 2 + ... + M^ k
    print (k,"\n", np. array (L, dtype = int ))

# bao đóng bắc cầu R∗ của R
# A = M*
np. array (A, dtype =int)


2 
 [[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
3 
 [[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
4 
 [[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


array([[0, 1, 1, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [ ]:
import numpy as np

#  Thuật toán Warshall
W = np.array([[0, 1, 0, 1],
              [0, 1, 0, 0],
              [1, 0, 0, 0],
              [0, 0, 1, 0]], dtype=bool)

n = len(W)

for k in range(n):
    for i in range(n):
        for j in range(n):
            W[i, j] += W[i, k] * W[k, j]
    print(k + 1,"\n", np.array(W, dtype=int))

1 
 [[0 1 0 1]
 [0 1 0 0]
 [1 1 0 1]
 [0 0 1 0]]
2 
 [[0 1 0 1]
 [0 1 0 0]
 [1 1 0 1]
 [0 0 1 0]]
3 
 [[0 1 0 1]
 [0 1 0 0]
 [1 1 0 1]
 [1 1 1 1]]
4 
 [[1 1 1 1]
 [0 1 0 0]
 [1 1 1 1]
 [1 1 1 1]]


In [8]:
from sympy import *

n = symbols('n')
F = symbols('F', cls=Function)
rsolve(
    -F(n) + F(n - 1) + F(n - 2),
    F(n),
    {F(0): 0, F(1): 1}
)

-sqrt(5)*(1/2 - sqrt(5)/2)**n/5 + sqrt(5)*(1/2 + sqrt(5)/2)**n/5